// <auto-generated />
namespace Trace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Newplc_tagstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Newplc_tagstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006080255041_New plc_tags table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
