// <auto-generated />
namespace Trace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addtightening_repairstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtightening_repairstable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007160445335_Add tightening_repairs table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
