// <auto-generated />
namespace Trace.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddLengthcolumntoPLCTagtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLengthcolumntoPLCTagtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006250335132_Add Length column to PLCTag table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
